apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
    nginx.org/client-max-body-size: 2000m
  name: fuchicorp-docker-ingress
spec:
  rules:
  - host: docker.{{ .Values.domain_name}}
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-service
          servicePort: {{ .Values.nexusport }}
      - path: /v2/
        backend:
          serviceName: nexus-service
          servicePort: {{ .Values.repo_port }}
  tls:
  - hosts:
    - docker.{{ .Values.domain_name}}
    secretName: tls-docker-prod-cert
